### ISSUE TITLE
Error when yearly seasonality is enabled

### ISSUE THREAD

**Issue by nialloulton** [pymc-labs/pymc-marketing#462]
Also have confirmed date column doesn't have duplicate values.

```
File /opt/conda/lib/python3.10/site-packages/pymc_marketing/mmm/validating.py:44, in ValidateDateColumn.validate_date_col(self, data)
     42     raise ValueError(f"date_col {self.date_column} not in data")
     43 if not data[self.date_column].is_unique:
---> 44     raise ValueError(f"date_col {self.date_column} has repeated values")

ValueError: date_col Weeks has repeated values
```

**Comment by wd60622** [comment]
I believe this has been fixed. Do you remember the status? @juanitorduz 

related to #402 #346

**Comment by juanitorduz** [comment]
Yes! I will close this one

**Comment by sonriks6** [comment]
I'd say the error is still there if by default you enable yearly_seasonality=2 and have a low number of observations

**Comment by wd60622** [comment]
> I'd say the error is still there if by default you enable yearly_seasonality=2 and have a low number of observations

Hi, are you able to post a reproducible example with the latest main branch?
